### ISSUE TITLE
NyElectrics doesn't seem to work on v9.7.9

### ISSUE THREAD

**Issue by ThreePounds311** [tedoxdev/NyElectrics#2]
It's all in the title :)

Log :

`[18:15:12.893]` [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(84,30): error CS0506: "NyElectricBlastFurnaceObject.Destroy()": Der geerbte Member "WorldObject.Destroy()" kann nicht überschrieben werden, da er nicht als "virtual" , "abstract" oder "override" markiert ist.
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsCementKiln.cs(79,30): error CS0506: "NyElectricCementKilnObject.Destroy()": Der geerbte Member "WorldObject.Destroy()" kann nicht überschrieben werden, da er nicht als "virtual" , "abstract" oder "override" markiert ist.

[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsCementKiln.cs(99,80): error CS0103: Der Name "InPageTooltip" ist im aktuellen Kontext nicht vorhanden.
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsCementKiln.cs(99,71): error CS1739: Die beste Überladung für "EcopediaAttribute" enthält keinen Parameter mit dem Namen "display".
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(100,80): error CS0103: Der Name "InPageTooltip" ist im aktuellen Kontext nicht vorhanden.
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(100,71): error CS1739: Die beste Überladung für "EcopediaAttribute" enthält keinen Parameter mit dem Namen "display".
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsCementKiln.cs(71,51): error CS1501: Keine Überladung für die Initialize-Methode nimmt 1 Argumente an.
 
[18:15:12.893] [1] [ Info] [Eco] eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(74,51): error CS1501: Keine Überladung für die Initialize-Methode nimmt 1 Argumente an.
 
[18:15:12.893] [4] [ Info] [Eco] Server Initialization                             ... Finished in 9,698 sec
 
[18:15:12.893] [1] [Error] [Eco] Failed to start the server. Exception was Exception: Exception
Message: eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(84,30): error CS0506: "NyElectricBlastFurnaceObject.Destroy()": Der geerbte Member "WorldObject.Destroy()" kann nicht überschrieben werden, da er nicht als "virtual" , "abstract" oder "override" markiert ist.
Source:Eco.ModKit

System.Exception: eco\Mods\UserCode\TedoxMods\NyElectrics\NyElectricsBlastFurnace.cs(84,30): error CS0506: "NyElectricBlastFurnaceObject.Destroy()": Der geerbte Member "WorldObject.Destroy()" kann nicht überschrieben werden, da er nicht als "virtual" , "abstract" oder "override" markiert ist.
   at Eco.ModKit.RoslynCompiler.HandleCompilerError(ImmutableArray`1 diagnostics)
   at Eco.ModKit.RoslynCompiler.Compile(AssemblyLoadContext assemblyContext)
   at Eco.ModKit.RoslynCompiler..ctor(AssemblyLoadContext assemblyContext, String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.RoslynCompiler..ctor(String modsDirectory, String modsAssemblyPath)
   at Eco.ModKit.ModKitPlugin..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
Outer Exceptions:
Exception has been thrown by the target of an invocation.`
